travis-ci: update distros list in the build matrix
Build against the same distros as tarantool except CentOS 6.

The following build time error appears on CentOS 6:

 | <...>/smtp/smtpc.c:91:30: error: ‘CURLOPT_MAIL_FROM’ undeclared

I guess it is due to very old curl:

 | libcurl-devel.x86_64 0:7.19.7-53.el6_9.